/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_seasons_get"];
        put?: never;
        /** Create Season */
        post: operations["create_season_seasons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{season_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Season */
        get: operations["get_season_seasons__season_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_players_get"];
        put?: never;
        /** Create Player */
        post: operations["create_player_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_players__player_id__get"];
        put?: never;
        post?: never;
        /** Delete Player */
        delete: operations["delete_player_players__player_id__delete"];
        options?: never;
        head?: never;
        /** Update Player */
        patch: operations["update_player_players__player_id__patch"];
        trace?: never;
    };
    "/players/{player_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Stats */
        get: operations["get_player_stats_players__player_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Scores */
        post: operations["ingest_scores_ingest_scores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/player/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Stats */
        get: operations["player_stats_stats_player__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leaderboard */
        get: operations["leaderboard_stats_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/partnerships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Partnerships */
        get: operations["all_partnerships_stats_partnerships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/partnerships/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partnerships For Player */
        get: operations["partnerships_for_player_stats_partnerships__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/partnerships/{player_a_id}/{player_b_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Specific Partnership */
        get: operations["specific_partnership_stats_partnerships__player_a_id___player_b_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/head-to-head/{player_a_id}/{player_b_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Head To Head */
        get: operations["head_to_head_stats_head_to_head__player_a_id___player_b_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/matchup/{pair_a_ids}/vs/{pair_b_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matchup */
        get: operations["matchup_stats_matchup__pair_a_ids__vs__pair_b_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/partnerships/overplayed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partnerships Overplayed */
        get: operations["partnerships_overplayed_anomalies_partnerships_overplayed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/partnerships/underplayed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Partnerships Underplayed */
        get: operations["partnerships_underplayed_anomalies_partnerships_underplayed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/head-to-head/overplayed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Head To Head Overplayed */
        get: operations["head_to_head_overplayed_anomalies_head_to_head_overplayed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/head-to-head/underplayed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Head To Head Underplayed */
        get: operations["head_to_head_underplayed_anomalies_head_to_head_underplayed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasResponse */
        AliasResponse: {
            /** Id */
            id: number;
            /** Alias */
            alias: string;
        };
        /** AnomalyEntry */
        AnomalyEntry: {
            /** Player A Id */
            player_a_id: number;
            /** Player B Id */
            player_b_id: number;
            /** Actual */
            actual: number;
            /** Expected */
            expected: number;
            /** Deviation */
            deviation: number;
        };
        /** GameDetailResponse */
        GameDetailResponse: {
            /** Id */
            id: number;
            /** Played On */
            played_on: string;
            /** Session */
            session: number | null;
            /** Season Id */
            season_id: number;
            /** Game Number */
            game_number: number;
            /** Team A Score */
            team_a_score: number;
            /** Team B Score */
            team_b_score: number;
            /** Team A */
            team_a: components["schemas"]["GamePlayerRef"][];
            /** Team B */
            team_b: components["schemas"]["GamePlayerRef"][];
        };
        /** GamePlayerRef */
        GamePlayerRef: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
        };
        /** GameResponse */
        GameResponse: {
            /** Id */
            id: number;
            /** Played On */
            played_on: string;
            /** Session */
            session: number | null;
            /** Season Id */
            season_id: number;
            /** Game Number */
            game_number: number;
            /** Team A Score */
            team_a_score: number;
            /** Team B Score */
            team_b_score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadToHeadResponse */
        HeadToHeadResponse: {
            /** Player A Id */
            player_a_id: number;
            /** Player B Id */
            player_b_id: number;
            /** Games Played */
            games_played: number;
            /** Player A Wins */
            player_a_wins: number;
            /** Player B Wins */
            player_b_wins: number;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Files */
            files: string[];
        };
        /** IngestResponse */
        IngestResponse: {
            /** Games Loaded */
            games_loaded: number;
            /** Errors */
            errors: string[];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Player Id */
            player_id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate */
            win_rate: number;
            /** Avg Points */
            avg_points: number;
        };
        /** MatchupResponse */
        MatchupResponse: {
            /** Pair A */
            pair_a: number[];
            /** Pair B */
            pair_b: number[];
            /** Games Played */
            games_played: number;
            /** Pair A Wins */
            pair_a_wins: number;
            /** Pair B Wins */
            pair_b_wins: number;
        };
        /** PartnershipResponse */
        PartnershipResponse: {
            /** Player A Id */
            player_a_id: number;
            /** Player B Id */
            player_b_id: number;
            /** Games Together */
            games_together: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate */
            win_rate: number;
        };
        /** PlayerCreate */
        PlayerCreate: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
        };
        /** PlayerPartnershipResponse */
        PlayerPartnershipResponse: {
            /** Partner Id */
            partner_id: number;
            /** Games Together */
            games_together: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate */
            win_rate: number;
        };
        /** PlayerResponse */
        PlayerResponse: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases: components["schemas"]["AliasResponse"][];
            /**
             * Season Roles
             * @default []
             */
            season_roles: components["schemas"]["PlayerSeasonRoleResponse"][];
        };
        /** PlayerSeasonRoleResponse */
        PlayerSeasonRoleResponse: {
            /** Season Id */
            season_id: number;
            /** Is Sub */
            is_sub: boolean;
        };
        /** PlayerStatsResponse */
        PlayerStatsResponse: {
            /** Player Id */
            player_id: number;
            /** Games Played */
            games_played: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Win Rate */
            win_rate: number;
            /** Avg Points */
            avg_points: number;
        };
        /** PlayerUpdate */
        PlayerUpdate: {
            /**
             * Add Aliases
             * @default []
             */
            add_aliases: string[];
            /**
             * Remove Aliases
             * @default []
             */
            remove_aliases: string[];
        };
        /** SeasonCreate */
        SeasonCreate: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
        };
        /** SeasonResponse */
        SeasonResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_seasons_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonResponse"][];
                };
            };
        };
    };
    create_season_seasons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_seasons__season_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"][];
                };
            };
        };
    };
    create_player_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_players__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_players__player_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_stats_players__player_id__stats_get: {
        parameters: {
            query?: {
                player_ids?: number[];
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_scores_ingest_scores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_stats_stats_player__player_id__get: {
        parameters: {
            query?: {
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaderboard_stats_leaderboard_get: {
        parameters: {
            query?: {
                sort_by?: "win_rate" | "avg_points";
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_partnerships_stats_partnerships_get: {
        parameters: {
            query?: {
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnershipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    partnerships_for_player_stats_partnerships__player_id__get: {
        parameters: {
            query?: {
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPartnershipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    specific_partnership_stats_partnerships__player_a_id___player_b_id__get: {
        parameters: {
            query?: {
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path: {
                player_a_id: number;
                player_b_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnershipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_to_head_stats_head_to_head__player_a_id___player_b_id__get: {
        parameters: {
            query?: {
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path: {
                player_a_id: number;
                player_b_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeadToHeadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matchup_stats_matchup__pair_a_ids__vs__pair_b_ids__get: {
        parameters: {
            query?: {
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path: {
                pair_a_ids: string;
                pair_b_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_games_get: {
        parameters: {
            query?: {
                week?: number | null;
                player_id?: number | null;
                team?: string | null;
                vs?: string | null;
                season_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    partnerships_overplayed_anomalies_partnerships_overplayed_get: {
        parameters: {
            query?: {
                limit?: number;
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    partnerships_underplayed_anomalies_partnerships_underplayed_get: {
        parameters: {
            query?: {
                limit?: number;
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_to_head_overplayed_anomalies_head_to_head_overplayed_get: {
        parameters: {
            query?: {
                limit?: number;
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_to_head_underplayed_anomalies_head_to_head_underplayed_get: {
        parameters: {
            query?: {
                limit?: number;
                player_ids?: number[];
                season_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
