#!/usr/bin/env bash
set -euo pipefail

# Creates a Neon branch from the prod (main) branch and writes .env.local
# so docker-compose uses the Neon DB instead of the local postgres container.
#
# Usage: ./scripts/dev-data-setup.sh [branch-name]
#
# Requires NEON_API_KEY and NEON_PROJECT_ID — set them in .env.secrets or export them.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Load .env.secrets if present
if [[ -f "$REPO_ROOT/.env.secrets" ]]; then
  # shellcheck disable=SC1091
  set -a; source "$REPO_ROOT/.env.secrets"; set +a
fi

if [[ -z "${NEON_API_KEY:-}" ]]; then
  echo "Error: NEON_API_KEY is not set. Add it to .env.secrets or export it." >&2
  exit 1
fi
if [[ -z "${NEON_PROJECT_ID:-}" ]]; then
  echo "Error: NEON_PROJECT_ID is not set. Add it to .env.secrets or export it." >&2
  exit 1
fi

BRANCH_NAME="${1:-$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD | tr '/' '-')}"
ENV_FILE="$REPO_ROOT/.env.local"

if [[ -f "$ENV_FILE" ]]; then
  echo "Warning: $ENV_FILE already exists. Delete it first or run dev-data-teardown.sh." >&2
  exit 1
fi

echo "Creating Neon branch: $BRANCH_NAME"

RESPONSE=$(curl -sf -X POST \
  "https://console.neon.tech/api/v2/projects/${NEON_PROJECT_ID}/branches" \
  -H "Authorization: Bearer ${NEON_API_KEY}" \
  -H "Content-Type: application/json" \
  -d "{\"branch\": {\"name\": \"dev/${BRANCH_NAME}\"}, \"endpoints\": [{\"type\": \"read_write\"}]}")

BRANCH_ID=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['branch']['id'])")
DB_HOST=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['endpoints'][0]['host'])")

# Neon connection strings use the project's role name — default is typically the project name
# We read the role from the connection_uris if provided, otherwise use NEON_ROLE env var.
NEON_ROLE="${NEON_ROLE:-graphminton}"
NEON_DB="${NEON_DB:-graphminton}"
NEON_PASSWORD="${NEON_PASSWORD:-}"

if [[ -z "$NEON_PASSWORD" ]]; then
  echo "Warning: NEON_PASSWORD not set in .env.secrets — DATABASE_URL will be incomplete." >&2
  echo "Add NEON_PASSWORD to .env.secrets and re-run."
  DATABASE_URL="postgresql://${NEON_ROLE}:<password>@${DB_HOST}/${NEON_DB}?sslmode=require"
else
  DATABASE_URL="postgresql://${NEON_ROLE}:${NEON_PASSWORD}@${DB_HOST}/${NEON_DB}?sslmode=require"
fi

ADMIN_TOKEN_VAL="${ADMIN_TOKEN:-$(grep '^ADMIN_TOKEN=' "$REPO_ROOT/.env.secrets" 2>/dev/null | cut -d= -f2-)}"

cat > "$ENV_FILE" <<EOF
# Generated by dev-data-setup.sh — do not commit
NEON_BRANCH_ID=${BRANCH_ID}
DATABASE_URL=${DATABASE_URL}
EOF

# Docker Compose reads .env for variable interpolation (e.g. ADMIN_TOKEN in compose.yml)
cat > "$REPO_ROOT/.env" <<EOF
# Generated by dev-data-setup.sh — do not commit
NEON_BRANCH_ID=${BRANCH_ID}
DATABASE_URL=${DATABASE_URL}
ADMIN_TOKEN=${ADMIN_TOKEN_VAL}
EOF

echo ""
echo "Done. Neon branch created: dev/${BRANCH_NAME} (${BRANCH_ID})"
echo "Written: .env.local, .env"
echo ""
echo "Next steps:"
echo "  docker compose up"
echo ""
echo "To clean up when done:"
echo "  ./scripts/dev-data-teardown.sh"
